# See https://pre-commit.com for more info
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: "chore: auto-fix by pre-commit-hooks"
  autofix_prs: true
  autoupdate_commit_msg: "chore: pre-commit autoupdate"



repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff-format
        name: "ruff (format)"
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff
        name: "ruff (lint)"
        args: ["--fix"]
        language_version: python3


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: end-of-file-fixer
        exclude: "\\.png$|\\.jpg$|\\.jpeg$|\\.gif$|\\.webp$"
      - id: trailing-whitespace
        exclude: "\\.png$|\\.jpg$|\\.jpeg$|\\.gif$|\\.webp$"
      - id: check-merge-conflict
